export const courseData = [
  {
    id: 1,
    item: "engineering",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Engineering Course",
  },
  {
    id: 2,
    item: "engineering",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Engineering Course",
  },
  {
    id: 3,
    item: "engineering",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Engineering Course",
  },
  {
    id: 4,
    item: "medical",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Medical Course",
  },
  {
    id: 5,
    item: "medical",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Medical Course",
  },
  {
    id: 6,
    item: "medical",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Medical Course",
  },
  {
    id: 7,
    item: "foundation",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Foundation Course",
  },
  {
    id: 8,
    item: "foundation",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Foundation Course",
  },
  {
    id: 9,
    item: "foundation",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Foundation Course",
  },
  {
    id: 10,
    item: "foundation",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Foundation Course",
  },
  {
    id: 11,
    item: "foundation",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Foundation Course",
  },
  {
    id: 12,
    item: "distance",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Distance Learning",
  },
  {
    id: 13,
    item: "distance",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Distance Learning",
  },
  {
    id: 14,
    item: "distance",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Distance Learning",
  },
  {
    id: 15,
    item: "distance",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Distance Learning",
  },
  {
    id: 16,
    item: "distance",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Distance Learning",
  },
  {
    id: 17,
    item: "distance",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Distance Learning",
  },
  {
    id: 18,
    item: "distance",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Distance Learning",
  },
  {
    id: 19,
    item: "board",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Board Course",
  },
  {
    id: 20,
    item: "board",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Board Course",
  },
  {
    id: 21,
    item: "board",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Board Course",
  },
  {
    id: 22,
    item: "board",
    img: "https://tipa.in/wp-content/uploads/2021/05/Online-courses.jpg",
    description: "Board Course",
  },
];
